#!/bin/zsh
#by hunter
#check online machines in Network
figlet 'FUHD '|lolcat
echo '-Fast Up Hosts Discovering. \n-version:v2->UHD \nusing fping \nEnter NetworkIp/Subnetmask \nex:192.168.1.0/24'|lolcat
echo -n ">" && read ip
var1=$(echo $ip|cut -d '.' -f 1,2,3)  
var2=$(echo $ip|cut -d '/' -f 1)
var3=$(echo $ip|cut -d '/' -f 2)
if [[ $(ping -c 2 $var1.1|grep -o '64'|uniq) == 64 ]];then       #check if network reached or not
echo '>Network reached \n>>Discovering UP machines start ...\U1F985' $(date)|lolcat 
cd ~/Desktop/UHD/                             
fping -a -g $ip  2>/dev/null |tee "$var2-$var3"
echo -n "output to $(pwd) \nDone"   
else
echo '>Network unreachable \nDone'|lolcat
fi
cd -
